### ISSUE TITLE
Bug regarding attributes

### ISSUE THREAD

**Issue by StandingPadAnimations** [StandingPadAnimations/MCprep-Kaion#5]
```
Traceback (most recent call last):
  File "/home/USER/.config/blender/3.4/scripts/addons/MCprep_addon/mcprep_ui.py", line 811, in draw
    p.filepath = context.scene.mcprep_texturepack_path
AttributeError: 'MCPREP_OT_swap_texture_pack' object has no attribute 'filepath'
Traceback (most recent call last):
  File "/home/USER/.config/blender/3.4/scripts/addons/MCprep_addon/mcprep_ui.py", line 811, in draw
    p.filepath = context.scene.mcprep_texturepack_path
AttributeError: 'MCPREP_OT_swap_texture_pack' object has no attribute 'filepath'
Traceback (most recent call last):
  File "/home/USER/.config/blender/3.4/scripts/addons/MCprep_addon/mcprep_ui.py", line 811, in draw
    p.filepath = context.scene.mcprep_texturepack_path
AttributeError: 'MCPREP_OT_swap_texture_pack' object has no attribute 'filepath'
Traceback (most recent call last):
  File "/home/USER/.config/blender/3.4/scripts/addons/MCprep_addon/mcprep_ui.py", line 811, in draw
    p.filepath = context.scene.mcprep_texturepack_path
AttributeError: 'MCPREP_OT_swap_texture_pack' object has no attribute 'filepath'
```

Looks like there's an attribute bug, though I'm curious if it appears in a stable release of MCprep and/or Kaion. Until I test it, I'll just leave it here for later me to deal with

**Comment by StandingPadAnimations** [comment]
This seems to be related to the SimplePrep branch

**Comment by StandingPadAnimations** [comment]
The error was related to the following (the use of `EnumProperty` instead of `BoolProperty`) : 
https://github.com/StandingPadAnimations/MCprep-Kaion/blob/f49b555f106bcbe02b40b9f0998509d0ac268ecd/MCprep_addon/materials/prep.py#L122-L126
